pkg/f1/run/result.go, pkg/f1/run/run_cmd_test.go, pkg/f1/run/run_stage_test.go, pkg/f1/run/test_runner.go, pkg/f1/testing/cancellable_timer.go, pkg/f1/trace/trace.go, pkg/f1/trigger/api/iteration_worker.go, pkg/f1/trigger/users/users_rate.go
This commit was created with the changes in
https://github.com/form3tech/k6-tests/pull/505
What is this for?
This change fixes a bug that we had with the
TestParameterised:LimitedIterationsTest which was not returning the
correct iteration when completing. see
https://github.com/form3tech/k6-tests/issues/477
What has changed?
* There was a race condition with the CancellableTimer where it would
block on cancel. Also a panic was being masked when cancel was being
called more than once and the channel being closed. The blocking was
fixed by moving the CancellableTimer channel receive read to a go
routine that blocks and waits for a send on the channel.
* Also added detailed tracing so that it is easier to debug these
issues in the future. It can be turned on by setting an environment …
=> Fixed a race condition causing flakey test runs

pkg/f1/run/run_cmd_test.go, pkg/f1/run/run_stage_test.go, pkg/f1/run/test_runner.go, pkg/f1/trigger/api/iteration_distribution.go, pkg/f1/trigger/api/iteration_distribution_test.go, pkg/f1/trigger/constant/constant_rate.go, pkg/f1/trigger/gaussian/gaussian_rate.go, pkg/f1/trigger/staged/staged_rate.go
Add different distribution modes for the constant, staged and gaussian triggers. The default distribution is regular.
The motivation of distributing the load is to be more effective when the request are resolved very fast.
=> Rate distribution for multiple trigger modes

pkg/f1/run/result.go, pkg/f1/run/test_runner.go, pkg/f1/trigger/api/iteration_distribution.go
- Remove unnecessary locker which can produce a dead-lock.
- Make distribution more optimal, when the iteration duration is 100ms there is no need to distribute.
=> Reduce tests flakyness

pkg/f1/run/test_runner.go, pkg/f1/testing/active_scenario.go, pkg/f1/testing/t.go
We currently log 1-2 errors per iteration failure, depending on the cause of the error, one of them containing no context around the problem. This PR simplifies it to log a single ERROR level message per failed iteration.
=> reduce duplicate reporting of errors

pkg/f1/options/run_options.go, pkg/f1/run/run_cmd.go, pkg/f1/run/test_runner.go, pkg/f1/testing/active_scenario.go, pkg/f1/testing/t.go
Simplify `testing.T` by removing environment variable map from it because it's not used much. Scenarios may use `os.Getenv()` to fetch environment variables where necessary.
=> Remove environment variable map from testing.T

pkg/f1/f1_root_cmd.go
This change sets a number of global HTTP transport defaults in order to allow for higher HTTP throughput when requesting HTTP services at a high number of iterations/s.
=> Add defaults for HTTP transport settings that make sense for loadtesting

internal/run/run_stage_test.go, pkg/f1/testing/t.go
This PR add methods `Logger()` and `Require()` to `testing.T` in order to allow others to define a meaningful interface on top of `testing.T` (for example `f1-tests`). With this change, `f1-tests` doesn't need to depend on `f1` anymore by defining an appropriate interface.
=> Add methods Logger() and Require() on testing.T

internal/run/active_scenario.go, internal/run/result.go, internal/run/run_cmd_test.go, internal/run/test_runner.go, pkg/f1/testing/t.go
The teardown function for the scenario setup phase was previously called manually, but when a scenario setup failed, it wasn't called at all. We now defer its execution so it will always be called properly.
This also fixes an issue with the test reporter that reported the setup phase as passing with a green checkmark when in fact it failed.
More improvements should be made to error reporting to make it clear during which phase of which stage (e.g. run of setup, teardown of setup, run of iteration, teardown of iteration) an error happened now that we have a `t.Cleanup()` style teardown handling. This would go in another PR though.
=> Ensure that scenario setup teardown is called

internal/run/result.go
This PR fixes the test duration printed at the end of a scenario in cases where the setup failed.
Before this PR:
```
Load Test Failed
Error: setup failed
0 iterations started in 292 years 24 weeks 3 days 23 hours 47 minutes 16 seconds 854 milliseconds 775 microseconds (0/second)
```
With this PR:
```
Load Test Failed
Error: setup failed
0 iterations started in 0 seconds (0/second)
```
=> Report run duration for runs without any iterations as 0 seconds

README.md
I was reading through the README.md and discovered that the link for trigger modes referred to a presently invalid URL. I have adjusted it to the one that I believe is the intended directory.
=> Correct the link regarding trigger modes

internal/trigger/file/stages_worker.go
When running a stage configured loadtest, the agent always take 100% of a core, as there is a spin in a select in the file internal/trigger/file/stages_worker.go .
With this MR, it only tick when there is something to do.
=> Remove default case to reduce cpu consumption

internal/run/main_test.go, internal/run/prom_push_gw_test.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/run/test_runner.go
Adds new ENV based configuration option that allows to export `namespace` label with prometheus metrics. As F1 is using `pushgateway` to export metrics, this change reduces chances for collisions. `pushgateway` under the hood acts like a simple cache, and it is overriding values when exactly the same set of labels are used.
=> feat: add configurable namespace label to prometheus metrics

internal/run/prom_push_gw_test.go
Fix to the test introduced as a part of this PR: https://github.com/form3tech-oss/f1/pull/145
Turned out to be flaky (~1 failure every 100 runs locally)
=> test: fix grouped labels in the fake prometheus

internal/run/main_test.go, internal/run/run_cmd_test.go, internal/run/test_runner.go
Metrics are exported via prometheus push gateway. Unfortunately, push gateway is only a super simple cache. It does not add any common labels, such as server, or pod name, and when metric with the same label set is provided, it overrides the latest value with a new one. That's why it's crucial to make label values unique.
With the new `id` label it should be a little easier. It's optional and needed only when metric entries might be not unique.
=> feat: optional id label for all metrics

go.mod, go.sum, internal/run/output.go, internal/run/result.go, internal/run/templates/templates.go, internal/run/test_runner.go, internal/termcolor/termcolor.go, internal/trace/console_tracer.go
https://github.com/workanator/go-ataman has not been updated in 7 years.
Replace with `strings.ReplaceAll` of the templated terminal colors.
Changes:
- templates are no longer global
- do the term color replacement only once when templates are loaded, instead of every render.
=> chore: rework templating & remove go-ataman

internal/metrics/metrics.go, internal/run/result.go, internal/run/run_stage_test.go, internal/run/test_runner.go
Extract all the magic strings to constants and no longer panic on unknown value of the result metric.
While it does indicate some internal problem. We should avoid panicing in libraries.
Continued effort to reduce logging usage for an https://github.com/form3tech-oss/f1/issues/173 and https://github.com/form3tech-oss/f1/issues/183.
=> chore(metrics): remove magic strings & panic

.golangci.yml, internal/metrics/metrics.go
After removing most the global usages we had in:
- #181
- #169
- #166 
We can now enforce the linter that will prevent more globals from being added[ to ease the maintainability](https://github.com/form3tech-oss/f1/issues/183)
=> chore: enable gochecknoglobals linter

go.mod, go.sum, internal/run/test_runner.go
https://github.com/aholic/ggtimer has not been updated in 9 years.
The dependency is not needed as the code is quite simple.
=> chore: remove ggtimer dependency

go.mod, go.sum, internal/gaussian/gaussian.go, internal/trigger/gaussian/gaussian_rate.go, internal/trigger/gaussian/gaussian_rate_bench_test.go, internal/trigger/gaussian/gaussian_rate_test.go
Replace https://github.com/chobie/go-gaussian with custom implementation.
Changes:
- go-gausian uses a custom `Erfc` function, that is slower than the one in the `math`. The custom implementatation calculates an approximation of the complementary error function using a polinomial. https://github.com/chobie/go-gaussian/blob/53c09d90eeaff40b27cd89352937d02d57dac506/gaussian.go#L43-L55
- Use constants for sqrt of 2 and sqrt of 2*Pi
- Avoid math.Pow(x, 2) and just multiply
- Avoid math.Sqrt by providing the standard deviation instead of the variance
- Carefullly document
```
→ benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/form3tech-oss/f1/v2/internal/trigger/gaussian
│     old.txt     │             new.txt              │
│     sec/op      │     sec/op       vs base …
```
=> chore: redo gauss calculations

.golangci.yml, internal/chart/chart_cmd.go, internal/chart/chart_cmd_stage_test.go, internal/console/printer.go, internal/run/run_cmd.go, internal/run/run_stage_test.go, internal/run/test_runner.go, internal/support/errorh/handler.go, pkg/f1/f1_scenarios.go, pkg/f1/root_cmd.go, pkg/f1/scenarios/scenarios_cmd.go
avoid raw `fmt.Print*` funcs to allow capturing ouput without globals
=> chore: inject printer to allow output stream redirect

internal/chart/chart_cmd.go, internal/run/active_scenario.go, internal/run/run_cmd.go, internal/run/templates/templates.go, internal/trigger/api/iteration_distribution.go, internal/trigger/constant/constant_rate.go, internal/trigger/gaussian/gaussian_rate.go, internal/trigger/ramp/ramp_rate.go, internal/trigger/rate/rate.go, internal/trigger/staged/staged_rate.go, internal/triggerflags/flags.go
- Extract flag names to constants to avoid possible misalignment between defining the flag and using it.
- metrics: use constant name for `dropped` instead of string literal
- rework `run` command flag setup to make it obvious how `IgnoreCommonFlags` is applied.
- Verbose error when `concurrency` is negative instead of a generic "invalid value".
- Extract distribution types to constants to avoid possible misalignment.
=> chore: constant flag names

internal/options/run_options.go, internal/run/run_cmd.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/run/test_runner.go, internal/trigger/api/api.go, internal/trigger/file/file_parser.go, internal/trigger/file/file_parser_test.go, internal/trigger/file/file_rate.go, pkg/f1/f1_scenarios_stage_test.go, pkg/f1/testing/t.go
Using types makes sure that all the access is protected.
Changes:
- Change iterations to uint32 instead of int32 (always positive)
- Minor test stage refactor
=> chore: use atomic types instead of function on primitives

internal/console/printer.go, internal/run/logging.go, internal/run/test_runner.go
Removes more hardcoded usages of os.Stdout for cleaner test output
Part of: #172
=> fix: use the printer output stream instead of os.Stdout

internal/run/run_cmd_test.go
Run the test for longer to allow more samples, as with the current setup, it is possible for all the samples to randomly be distributed in the same 100ms window.
Part of: #182
=> chore: fix TestRandomDistribution test

go.mod
Fixes CodeQL warning:
> As of Go 1.21, toolchain versions must use the 1.N.P syntax.
>
> 1.22 in go.mod does not match this syntax and there is no additional toolchain directive, which may cause some go commands to fail.
=> chore: add toolchain to go.mod

.github/workflows/ci.yaml, .github/workflows/codeql.yml
Following:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
Specifying `read` on `contents` implies everything else is `none` by default.
Fixes:
https://github.com/form3tech-oss/f1/security/code-scanning/1
https://github.com/form3tech-oss/f1/security/code-scanning/2
=> chore: add top level token permissions to CI jobs

go.mod
Second attempt at fixing codeql warning:
> As of Go 1.21, toolchain versions must use the 1.N.P syntax.
https://go.dev/doc/toolchain#version
Previous attempt: #209
=> chore: use full go version

internal/run/test_runner.go, internal/trace/console_tracer.go, internal/trace/nil_tracer.go, internal/trace/trace.go, pkg/f1/profiling.go
The variadic arguments in Go always lead to an allocation of a slice
before the function call.
To avoid the tracer having memory allocation overhead - use specific
function signatures.
=> fix(tracer): remove variadic arguments

internal/run/test_runner.go
Remove the `"iteration <n>"` prefix and just use `"<n>"` for the iteration field in `T`
It provides no value, as it's obvious from the field name, but leads to extra allocations.
=> feat(perf): change testing.T iteration value

pkg/f1/metrics/metrics.go
Don't expose internal metrics.
The internal metrics package is not documented, and interal uses are not isolated in a way where we can make changes without breaking user use cases in subtle ways.
The internal metrics are used for both pushing metrics to prometheus and reporting progress on command execution.
Prefer just to remove the API as it's an easy change for users to notice.
`testing.T.(Time)` is still available and well isolated from internal implementation.
While a breaking change would usually require a major version bump. In this case the user effort of migrating to a v3 would be higher than removing this usage.
=> BREAKING: don't expose internal metrics

.github/workflows/ci.yaml, pkg/f1/metrics/metrics.go
While the exported package has its own breaking changes. Prefer to restore it so CI steps don't fail.
=> Revert breaking metrics change

internal/metrics/metrics.go, internal/run/active_scenario.go, internal/run/result.go, internal/run/test_runner.go, pkg/f1/testing/t.go
Changes:
- Add a few methods to Metrics to be explicit about exactly what is
recorded.
- Reduce Progress summary objectives to only percentiles that are
printed out. No need to record everything if it's not used
- Remove Progress summary labels that are always constant during a run.
=> chore(metrics): simplify metric recording & progress

internal/run/test_runner.go, pkg/f1/f1_stage_test.go, pkg/f1/f1_test.go
When a scenario that was not added is called via CLI - f1 paniced:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104a8d114]
goroutine 1 [running]:
github.com/form3tech-oss/f1/v2/internal/run.NewActiveScenario(0x0, 0x1400020c5a0)
/Users/nikolayvladimirov/go/src/github.com/form3tech-oss/f1/internal/run/active_scenario.go:33 +0x24
github.com/form3tech-oss/f1/v2/internal/run.(*Run).Do(0x14000244000, {0x104cb02f0, 0x1400003e280}, 0x14000064020)
/Users/nikolayvladimirov/go/src/github.com/form3tech-oss/f1/internal/run/test_runner.go:121 +0x1b8
github.com/form3tech-oss/f1/v2/internal/run.Cmd.runCmdExecute.func1(0x1400020ef08, {0x1400003e370, 0x1, 0x5?}) …
```
=> fix: don't panic on unknown scenario name

pkg/f1/profiling.go
This reverts commit 265762f0509891a68947cdcdbb997be93c7221f1.
Aligns with documentation:
https://pkg.go.dev/runtime/pprof
=> Revert "chore(profiling): don't run GC on heap profile"

.golangci.yml, Makefile
https://golangci-lint.run/product/changelog/#v1580
=> chore: bump golangci-lint to 1.58.0

internal/trigger/file/file_parser.go, internal/trigger/staged/calculator.go, internal/trigger/staged/calculator_test.go, internal/trigger/staged/staged_rate.go
At the moment we have staged test jobs starting at midnight running for 20 hours, if a job is stopped for some reason, it can't be restarted as we don't want them to overlap.
I would like to specify start time when triggering the job, so that the stage is calculated based on that and not the time that the job was started, this would allow us to run a job every 10 minutes with a duration of 10m, so it self-recovers if a job is killed.
=> feat: support custom start-time for staged tests

benchcmd/main.go, internal/run/active_scenario.go, pkg/f1/testing/t.go
Handle immediate scenario termination via `panic`/`recover` instead of `Goexit`.
While `Goexit` is more efficient, for iterations that don't fail - it introduces performance overhead as we needed to create a short lived goroutine for each iteration.
=> feat: don't start a goroutine for each iteration

internal/chart/chart_cmd_stage_test.go, internal/run/run_stage_test.go, internal/trigger/file/file_parser_test.go, internal/trigger/file/file_rate.go, internal/trigger/gaussian/gaussian_rate.go
Raise log level to warn when running certain tests to avoid poluting the test output.
=> chore: cleanup test output

go.mod, go.sum, internal/run/run_stage_test.go
No need to have a full library dependency, for only two isolated test-only usages.
=> chore: remove avast/retry-go dependency

internal/run/templates/progress_test.go, internal/run/templates/templates.go
Use rounding functions to get a better iterations per second number.
Previously if the rate calculation always truncated to the closest second. Meaning, for 10 iterations in 980ms it reported 0 iterations per second. This change correctly reports a rate of 10/s.
=> fix(progress): fix rate per second reporting

benchcmd/main.go, internal/progress/average.go, internal/progress/stats.go, internal/run/test_runner.go, internal/trigger/api/iteration_worker.go, internal/trigger/users/users_rate.go, internal/workers/active_scenario.go, internal/workers/continuous_pool.go, internal/workers/queue_pool.go, internal/workers/workers.go, internal/xtime/nanotime.go, internal/xtime/nanotime_test.go
Rewrite worker pools to avoid internal lock usage in channels and context.Context.
Any time a lock is used it will drastically slow down execution as:
- needs to do a syscall to sleep, leading to a context switch out of user space
- the go scheduler will interrupt the current go routine and try to find a new one that can execute, leading to a massive overhead in the go scheduler. 
- **Change in behaviour**: previously the iteration trigger (constant, staged rate) would drop iterations if all workers are busy at time of trigger. Currently it will drop iterations not executed since the last trigger. Meaning the workers will try to execute as many iterations as they can before the next trigger and then drop, instead of dropping at time of trigger:
- Separate worker pool implementation for …
=> feat: rewrite work scheduling to improve performance

internal/trigger/api/iteration_distribution.go, internal/trigger/api/iteration_distribution_test.go
Co-authored-by: Kevin Intriago <kevin.intriago@form3.tech>
When using  very low rates intended to only fire the scenario a couple times over the duration, the calculations for the iteration distribution could fail to add up to 1 by the last tick of the iteration, missing executions (or failing to trigger the scenario at all if only 1 run was intended).
Using `Ceil` instead of `Round` ensures 1 is always reached consistently. See added test cases for examples that would fail to trigger the scenario without the fix.
=> Fix rounding on iteration-distribution calculations

pkg/f1/metrics/metrics.go
This exposes internal metrics that should not be accessed.
Ideally we want the flexibility to change them at will without breaking the API.
=> feat: deprecate GetMetrics()

internal/ui/output.go, pkg/f1/f1.go, pkg/f1/f1_stage_test.go, pkg/f1/f1_test.go
The built in logger, especially the JSON formater is very opinionated about the syntax and the fields to align with logrus behavior within the Form3 domain (such as `@timestamp` field name and the time formatting for it, etc.)
While we want to keep the defaults for ease of use, allow users to specify their own logger to align with their organizational ecosystem.
=> feat: support user provided loggers

internal/run/run_cmd.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/run/test_runner.go, internal/ui/printer.go
In case an interation is stuck for whatever reason f1 will never exit.
This adds a 10s timeout to wait for active iterations to complete.
=> fix: exit after a timeout on stuck iterations

internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/testdata/config-file-issue-268.yaml, internal/trigger/users/users_rate.go
Fixes #268
When a stage with `users` mode is run:
1. Starts a go routine with the worker
2. That go routine exits immediately as it only starts the pool.
3. It will then cancel the pool context and the test will immediately exit, ignoring max duration for the test
To avoid this wait for the pool to complete (reaching context timeout on the duration or max iterations) as part of the pool executor itself.
This is not a problem when `users` is run outside of a staged run as the top level runner will always wait for completion before cancelling the worker context.
=> fix: users in a staged run would exit immediately without max iterations

.github/workflows/ci.yaml
Currently pull requests from forks don't trigger the test suite.
This allows the test suite to run on pull requests from forks after manual approval by a codeowner.
=> chore(ci): allow tests to run on Pull Requests

README.md, internal/envsettings/env.go, pkg/f1/f1.go
The change is needed for back-compatibility with previous versions when `LOG_LEVEL` and `LOG_FORMAT` were not used to control f1 outputs (introduced here https://github.com/form3tech-oss/f1/pull/260)
As these are quite common env variable names, they are currently over-scoped. F1 users might want to use custom loggers within their own scenarios that rely on such environment variables and configure them differently than f1 runner itself.
`LOG_FILE_PATH` variable stays the same for back-compatibility as it was present for a long time.
=> fix: Add F1_ prefix to over-scoped LOG_LEVEL, LOG_FORMAT environment variables

internal/metrics/metrics.go, internal/metrics/metrics_test.go
* Fix: Map traversing is unstable in go. This leaded to a mix of label/values with the previous implementation
=> Static metrics fixes
