pkg/f1/raterun/runner.go, pkg/f1/raterun/runner_test.go, pkg/f1/raterun/runner_test_stage.go, pkg/f1/run/test_runner.go, pkg/f1/testing/t.go
Fixes log output to console only when verbose flag is set.
Also some refactoring :)
=> Fix for verbose log output to file when flag is not set

.travis.yml
This hopefully automatically releases new patch versions of f1 on every merge to master
=> Auto-release for f1 lib on master branch

.travis.yml
get version regardless of suffix
=> Fix: Get the library in semantic versioning format

pkg/f1/metrics/metrics.go
=> Allowed metrics to be used externally

README.md
Add f1 tests output descrtiption
This release will cause no downtime in staging or production.
The old and new version will run happily together in parallel during deployment.
Paste a screenshot, link, or other proof that the change works.
=> Update readme with the output description

internal/trigger/constant/constant_rate.go, internal/trigger/gaussian/gaussian_rate.go, internal/trigger/gaussian/gaussian_rate_test.go, internal/trigger/ramp/ramp_rate.go, internal/trigger/rate/rate.go
Added new `peak-rate` parameter to Gaussian load test. 
It is used only when `volume` is not provided.
=> feat: gaussian test peak-rate parameter

internal/trigger/gaussian/gaussian_rate.go, internal/trigger/gaussian/gaussian_rate_test.go
- Gaussian test now properly uses repeat parameter to run and graph output data.
- Fix lint issue
=> Fix gaussian test to properly test and graph non default repeat

config-file-example.yaml, internal/options/run_options.go, internal/run/result.go, internal/run/run_cmd.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/run/test_runner.go, internal/testdata/config-file.yaml, internal/trigger/api/api.go, internal/trigger/file/file_parser.go, internal/trigger/file/file_parser_test.go, internal/trigger/file/file_rate.go
This PR is opened on behalf of @asambres-form3 to merge into the main branch.  The original work is [here](https://github.com/form3tech-oss/f1/pull/107).
* Add max failures option
* Add tests
---------
=> Add max failures option (#107)

internal/run/main_test.go
goleak provides `VerifyTestMain` for this use case, no need to have custom logic.
=> chore: simplify goleak check

.golangci.yml, Makefile, internal/metrics/metrics.go, internal/raterun/runner.go, internal/run/fake_prometheus_test.go, internal/run/result.go, internal/run/run_cmd.go, internal/run/templates/templates.go, internal/run/test_runner.go, internal/trigger/api/iteration_distribution.go, internal/trigger/constant/constant_rate.go, internal/trigger/file/file_parser.go, internal/trigger/gaussian/gaussian_rate.go, internal/trigger/ramp/ramp_rate.go, internal/trigger/staged/calculator.go, internal/trigger/staged/stage.go, internal/trigger/staged/staged_rate.go, pkg/f1/doc.go, pkg/f1/f1_scenarios_stage_test.go, pkg/f1/testing/doc.go, pkg/f1/testing/t.go
Enable:
- gocritic
- prealloc
- lll
Permanently disable:
- dupl
=> chore: enable more linters

internal/metrics/metrics.go, internal/metrics/result.go, internal/run/active_scenario.go, internal/run/run_cmd.go, internal/run/run_stage_test.go, internal/run/test_runner.go, pkg/f1/root_cmd.go
=> chore: allow using non-global metrics instance

go.mod, go.sum, internal/run/active_scenario.go, internal/run/run_stage_test.go
- Remove unused `id` in `ActiveScenario`
- Use descriptive scenario names instead of UUID
- Remove `github.com/google/uuid` dependency
#170
=> chore: remove uuid dependency & more readable test output

.golangci.yml, Makefile, internal/chart/chart_cmd_test.go, internal/raterun/runner_test.go, internal/run/logging_test.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/trigger/api/iteration_distribution_test.go, internal/trigger/file/file_parser_test.go, internal/trigger/gaussian/gaussian_rate_test.go, internal/trigger/staged/stage_test.go, pkg/f1/f1_scenarios_test.go
They still run sequentially on the CI as the suite fails
Part of #172
=> chore: allow running tests in parallel

.github/workflows/scorecard.yml
https://github.com/ossf/scorecard?tab=readme-ov-file#what-is-scorecard
=> OpenSSF Scorecard

internal/fluentd/hook.go, internal/run/logging.go, internal/run/test_runner.go, internal/support/errorh/handler.go, internal/trigger/file/stages_worker.go, internal/trigger/staged/calculator.go, pkg/f1/testing/t.go
Changes:
- Remove `logrus` alias to make it easier to track usages
- Remove unused `WithField` calls in `NewT`
`logrus.WithField` adds a data to `logrus.Entry`, the `Logger` itself doesn't carry the extra fields. The added fields were never used. Just remove them.
Proof that the fields were not added:
=> feat: logger changes

.github/workflows/scorecard.yml
=> chore: fix scorecard upload

.gitignore, Makefile, benchcmd/main.go
Add a command with test scenarios to be used for benchmarking
=> chore: add cmd to be used for benchmarking

internal/options/run_options.go, internal/run/result.go, internal/run/run_cmd.go, internal/run/run_cmd_test.go, internal/run/run_stage_test.go, internal/run/test_runner.go, internal/trace/console_tracer.go, internal/trace/nil_tracer.go, internal/trace/trace.go, internal/trigger/api/api.go, internal/trigger/file/file_parser.go, internal/trigger/file/file_parser_test.go, internal/trigger/file/file_rate.go, pkg/f1/f1_scenarios_stage_test.go
Increase the time it takes to overflow the iteration counter
=> feat: increase iteration counter to uint64

internal/run/active_scenario.go, internal/run/test_runner.go, pkg/f1/testing/t.go
Use a pool of pre-allocated structs to hold iteration state, instead of allocating each time.
=> feat: remove per iteration allocations

.golangci.yml, internal/chart/chart_cmd_stage_test.go, internal/chart/chart_cmd_test.go, internal/run/logging.go, internal/run/logging_test.go, internal/trigger/api/iteration_distribution.go, internal/trigger/api/iteration_distribution_test.go, internal/trigger/constant/constant_rate.go, internal/trigger/file/file_parser.go, internal/trigger/file/file_parser_test.go, internal/trigger/file/file_rate.go, internal/trigger/file/stages_worker.go, internal/trigger/gaussian/gaussian_rate.go, internal/trigger/gaussian/gaussian_rate_bench_test.go, internal/trigger/gaussian/gaussian_rate_test.go, internal/trigger/ramp/ramp_rate.go, internal/trigger/staged/calculator.go, internal/trigger/staged/calculator_test.go, internal/trigger/staged/stage.go, internal/trigger/staged/stage_test.go, internal/trigger/staged/staged_rate.go
Make sure all tests are separated in a `_test` package
=> chore: enable testpackage linter

README.md
- Add LOG_LEVEL and LOG_FORMAT docs
- Fix LOG_FILE_PATH docs
- Cleanup
=> chore: Cleanup README.md
